### ISSUE TITLE
How to use a different WordNet

### ISSUE THREAD

**Issue by guategeek** [TfTHacker/Obsidian-WordNet#2]
Hey first off cool plugin! I just tried it out and like it a lot better than the other dictionary plugin I have. Also I'm excited that I can create my own custom dictionary's for words that I come up with in creating my own stories and worlds and such.

I was wondering if there is a way to set up the plugin to use a different WordNet. I ask because I do a lot of writing in two languages (English & Spanish in my case) and I would love to have a dictionary with both. I had never heard of WordNet before this, but I searched around the internet and found that there seem to be other WordNet's ones for different languages and multilingual ones as well.

[Wordnets in the World](http://globalwordnet.org/resources/wordnets-in-the-world/)
[Open Multilingual Wordnet](http://compling.hss.ntu.edu.sg/omw/)

I'm not a programmer/web tech kind of person so I have no clue how one would use these other WordNet's. I was wondering if you would be willing to add some sort of functionality to your awesome plugin for using other WordNets; or if you could point me in the right direction for how I could us them myself.

**Comment by TfTHacker** [comment]
Hi, so glad to hear from you. It would be possible for plugin to use different data. But it would likely require a little programming work. I exported the english WordNet to a format that would work well for the plugin. 

So it would not be hard, but you or someone else would have to make the file.
