### ISSUE TITLE
Feature Request: Allow adding just the word itself

### ISSUE THREAD

**Issue by lmeerwood** [TfTHacker/Obsidian-WordNet#3]
I use the WordNet plugin quite a bit to verify words I don't quite now how to spell. Would it be possible to add an option (maybe a toggle in the settings) so when we select a word from the list it paste in just the word without any formatting or the definition? Thanks heaps for the great library!

**Comment by TfTHacker** [comment]
This project is using the default controls of obsidian and I don't think I can strip the clipboard of extra content before they are used in the control.

**Comment by cwittern** [comment]
Jumping in here from the sidelines; if I understand correctly what the OP wanted to achieve, this can be done by editing the template to have just {term} and nothing else. 
Hope this helps.
