### ISSUE TITLE
Mobile app crashing when this plugin enabled.

### ISSUE THREAD

**Issue by ertugruluyar-github** [TfTHacker/Obsidian-WordNet#4]
I am using GM 5 Plus D mobile phone. Android 8. 
Obsidian mobile version: 1.4.3 (95)
API v1.1.16

**Comment by TfTHacker** [comment]
I don't have an android to test this on. I did update thee libraries used by this plugin, maybe this will help.

Also note that I have updated the icon for ribbon bar to make it consistent with all the UI updates of obsidian. Please let me know if the project works now.

**Comment by ertugruluyar-github** [comment]
Thank you, I tested and the problem still happening. Also app opening time is increased, loading, loading and crash.

**Comment by TfTHacker** [comment]
I'm sorry to hear that. I can't reproduce it. One suggestion is to uninstall the plugin and make sure that the folder was deleted from your .obsidian/obsidian-wordnet folder. Then reinstall the plugin.

Let me know if that works.

**Comment by ertugruluyar-github** [comment]
When I uninstalled the app, the folder was deleted automatically by obsidian.
Whatever, thank you anyway for your helps.

**Comment by TfTHacker** [comment]
Well, the folder isn't always deleted since the dictionary downloads a dictionary file, but perhaps it is on android. I am sorry I can't reproduce this issue.

**Comment by Modmanri** [comment]
I would like to add that I just had this problem start as well. Deleting the plugin, and going to a week old backup won't allow it to start. It's puzzling

Pixel 3a, Android 11, Obsidian 1.4.16
